### ISSUE TITLE
No Dockerfile?

### ISSUE THREAD

**Issue by letsgolesco** [Starefossen/docker-transporter#1]
Was just googling for compose transporter dockerfiles to see how other people did it - noticed your repo doesn't have a Dockerfile. Forgot to push it?

**Comment by Starefossen** [comment]
Yes, totally forgot to push! My bad! I have pushed the Dockerfile now :)

**Comment by Starefossen** [comment]
This Docker Image is now avaiable from the official Docker Registry Hub: https://hub.docker.com/r/starefossen/transporter/

```
docker pull starefossen/transporter:0.1
```
