### ISSUE TITLE
No tag on docker hub

### ISSUE THREAD

**Issue by ssunzulily** [Starefossen/docker-transporter#2]
You got 0.1.1 here but not at https://hub.docker.com/r/starefossen/transporter/

**Comment by Starefossen** [comment]
Thanks for the ping @ssunzulily, I will look into it.

**Comment by Starefossen** [comment]
Fixed, I have added `:0.1.1`, `:0.1` and `:0` and `:latest` tags :)

https://hub.docker.com/r/starefossen/transporter/tags/
